### PR TITLE
Convert to functional

### PR DESCRIPTION
**Pull request by lynchdean**
Moved components to separate files

### CODE REVIEW

**Comment by Stetchy** [comment]
In each of the `function X(y) {...}` statements where you then have `const x = (y) => {...}` where `x` returns a JSX element you should instead split those functions into the individual components, so each of those `const x` will be it's own functional component - where it makes sense. If they are very small, they can be merged into one component, or if it makes sense to, use the compound component pattern.

**Comment by lynchdean** [comment]
Just did the Row inside Board.jsx first to make sure I'm doing it right

**Comment by Stetchy** [comment]
Yeah, that way is what I'd say is correct.

**Comment by lynchdean** [comment]
> In each of the `function X(y) {...}` statements where you then have `const x = (y) => {...}` where `x` returns a JSX element you should instead split those functions into the individual components, so each of those `const x` will be it's own functional component - where it makes sense. If they are very small, they can be merged into one component, or if it makes sense to, use the compound component pattern.

Think this is all done now :)

**Review by riain0 — APPROVED** [review]
Looks good - if you wanted you could break components down into more atomic parts, by following the Atomic Design pattern [here](https://bradfrost.com/blog/post/atomic-web-design/). Good work though - TypeScript next!

**Comment by lynchdean** [comment]
Thanks for the link, I'll add that to the list too haha

**Pull request merged**
